# Generated by Django 2.1a1 on 2018-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerName', models.CharField(max_length=10)),
                ('customerID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
