# Generated by Django 2.1a1 on 2018-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
